/**
 * Typed environment.
 *
 * - Server code reads bindings/secrets via `getCloudflareContext().env` (AppEnv).
 * - Browser code reads ONLY `NEXT_PUBLIC_*`. Secrets never get a NEXT_PUBLIC_ prefix.
 *
 * `CloudflareEnv` is GENERATED by `pnpm cf-typegen` → worker-configuration.d.ts. Re-run after
 * any wrangler binding change. Until first generation, this references a global type that
 * the generated file augments.
 */
export interface AppEnv extends CloudflareEnv {
  /** Base URL of the Hono backend worker API. Server-only. */
  API_BASE_URL: string;
  /** Optional shared secret for internal service-to-service calls. Never NEXT_PUBLIC_. */
  INTERNAL_SERVICE_SECRET?: string;
}

/** Client-side public config (safe to ship to the browser). */
export const publicEnv = {
  apiUrl: process.env.NEXT_PUBLIC_API_URL ?? "",
} as const;
